<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Mapping [ <!ELEMENT Mapping (Package+)> 
<!ATTLIST Package name CDATA #REQUIRED>
<!ATTLIST Package testData CDATA #IMPLIED> 
<!ATTLIST Package clientEnvironment CDATA #IMPLIED>
<!ATTLIST Package runStrategy (Full|Optimal) #IMPLIED> 
<!ELEMENT Package (Class*)>
<!ATTLIST Class name CDATA #REQUIRED>
<!ATTLIST Class clientEnvironment CDATA #IMPLIED>
<!ATTLIST Class testData CDATA #IMPLIED> 
<!ATTLIST Class runStrategy (Full|Optimal) #IMPLIED>
<!ELEMENT Class (MethodName*)>
<!ATTLIST MethodName name CDATA #REQUIRED> 
<!ATTLIST MethodName testData CDATA #IMPLIED> 
<!ATTLIST MethodName clientEnvironment CDATA #IMPLIED> 
<!ATTLIST MethodName runStrategy (Full|Optimal) #IMPLIED>]>

<Mapping>
	
	<Package name="tests" >
		<Class name="tests.AddShipwreckTest"  runStrategy="Optimal"  clientEnvironment="ChromeFFIE.xml">
			<MethodName name = "tests.AddShipwreckTest.addShipwreckTest" testData="AddTestData.xml" />
		</Class>
		<Class name="tests.UpdateShipwreckTest"  runStrategy="Optimal"  clientEnvironment="FF.xml">
			<MethodName name = "tests.UpdateShipwreckTest.updateShipwreckTest" testData="UpdateTestData.xml" />
		</Class>
		<Class name="tests.DeleteShipwreckTest"  runStrategy="Optimal"  clientEnvironment="ChromeFF.xml">
			<MethodName name = "tests.DeleteShipwreckTest.deleteShipwreckTest" testData="DeleteTestData.xml" />
		</Class>
	</Package>
		
</Mapping>
